name: Cool Iceland
favicon: null
layout_spectrum: 0.09944011038169265
typography_spectrum: 0.07565118465572596
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.15757363312877715
  lightness: 0.1561942573171109
  saturation: 0.08488505706191063
  rhythmicContrast: 0.14064088626764715
purpose: []
